### ISSUE TITLE
RFC: Leaderboard

### ISSUE THREAD

**Issue by stefan-it** [UKPLab/linspector#1]
Hi @gozdesahin,

thanks for releasing this framework and several datasets!

I would like to ask if you can add a kind of leaderboard, so that researchers can train their own models and report back the results.

Thanks + regards,

Stefan

**Comment by gozdesahin** [comment]
Thanks for the nice point @stefan-it . We actually thought about it but detected some potential problems. The biggest one is the different training conditions (e.g., corpora, tokenization, unk ratio, hyperparameters etc...) of the embeddings which would lead to unfair comparison. To make sure we compare the right things, we need to train them ourselves and that demands computational resources (which we may not be able to provide at the moment). Therefore we leave it as a TO-DO. If-one-day we can create an environment that would guarantee fair comparison, we will definitely do it!
